### Lab Assignments On Chapter-1

**Name** - Amulya Shrivastava  
**Registration Number** - 2341019456  
**Section** - 23412F3  
**Serial Number** - 60  

In [11]:
# Question 1
marks=int(input("Enter students marks: "))
if 90<=marks<=100:
    print("Got grade A")
elif 75<=marks<=89:
    print("Got grade B")
elif 50<=marks<=74:
    print("Got grade C")
else:
    print("Fail")

Got grade A


In [12]:
# Question 2
num=int(input("Enter a number: "))
number,sum=num,0
while num>0:
    sum+=num%10
    num//=10
print("The sum of digits in ",number," is ",sum)

The sum of digits in  2341019456  is  35


In [13]:
# Question 3
import math
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(math.sqrt(n)+1)):
        if n%i==0:
            return False
    return True
print("Is 7 prime? ",is_prime(7))
print("Is 10 prime? ",is_prime(10))
print("Is 23 prime? ",is_prime(18))

Is 7 prime?  True
Is 10 prime?  False
Is 23 prime?  False


In [14]:
# Question 4
def is_palindrome(word):
    return word==word[::-1]
print('Is "madam" a palindrome? ',is_palindrome("madam"))
print('Is "hello" a palindrome? ',is_palindrome("hello"))

Is "madam" a palindrome?  True
Is "hello" a palindrome?  False


In [15]:
# Question 5
import numpy as np
matrix1=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matrix2=np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

# a) Matrix multiplication
matrix_mul=np.dot(matrix1, matrix2)
print("Matrix Multiplication/Dot Product:\n",matrix_mul)

# b) Determinant of a matrix
det_matrix1=np.linalg.det(matrix1)
print("\nDeterminant of matrix1: ",det_matrix1)

# c) Inverse of a matrix
det_matrix2=np.linalg.det(matrix2)
if det_matrix2!=0:
    inv_matrix2=np.linalg.inv(matrix2)
    print("\nInverse of matrix2:\n",inv_matrix2)
    identity_matrix=np.dot(matrix2,inv_matrix2)
    print("\nVerification :\n",np.round(identity_matrix))
else:
    print("No inverse exists\n")

Matrix Multiplication/Dot Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Determinant of matrix1:  0.0
No inverse exists



In [16]:
# Question 6
import numpy as np
arr1=np.random.randint(0,100,10)
arr2=np.random.randint(0,100,10)
print("Array 1: ",arr1)
print("Array 2: ", arr2)
print("\nArray1>Array2: ",arr1>arr2)
print("Array1<Array2: ",arr1<arr2)
print("Array1==Array2: ",arr1==arr2)
check=np.sum(arr1>arr2)
print("\nValue based comparision check: ",check," times")

Array 1:  [81 69 91 30 46 65 64 95 31  0]
Array 2:  [99 51 71 78 79 74 60 24 43 79]

Array1>Array2:  [False  True  True False False False  True  True False False]
Array1<Array2:  [ True False False  True  True  True False False  True  True]
Array1==Array2:  [False False False False False False False False False False]

Value based comparision check:  4  times


In [17]:
# Question 7
import numpy as np
marks=[88,92,80,75,60,55,95,82,78,85]
marks_arr=np.array(marks)

# a) Average marks
avg=np.mean(marks_arr)
print("Average marks: ",avg)

# b) Students who scored above average
average_marks=marks_arr[marks_arr>avg]
print("Students who scored above average: ",average_marks)

Average marks:  79.0
Students who scored above average:  [88 92 80 95 82 85]


In [18]:
# Question 8
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print("Original 4x4 Array:\n",arr)

# a) Extract the second row
Srow_get=arr[1]
print("\nSecond row:",Srow_get)

# b) Extract the third column
Tcolumn_get=arr[:,2]
print("\nThird column:",Tcolumn_get)

# c) Slice the sub-matrix of shape (2x2) from the bottom-right corner
submatrix=arr[2:,2:]
print("\nSub-matrix representation:\n",submatrix)

Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second row: [5 6 7 8]

Third column: [ 3  7 11 15]

Sub-matrix representation:
 [[11 12]
 [15 16]]


In [19]:
# Question 9
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print("Original Array:\n",arr)
reshaped=arr.reshape(2,6)
print("\nReshaped Arr:\n",reshaped)
raveled=arr.ravel()
print("\nRaveled Arr:",raveled)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped Arr:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Raveled Arr: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
# Question 10
import numpy as np
rolls=np.random.randint(1,7,1000)
frequency={face:np.sum(rolls==face) for face in range(1, 7)}
print("Frequency for each outcome:\n",frequency)

Frequency for each outcome:
 {1: np.int64(172), 2: np.int64(159), 3: np.int64(170), 4: np.int64(181), 5: np.int64(165), 6: np.int64(153)}
