### Part-B Question's Solution

#### MLC Minor Assignment - 2

![Image](./Data/Assignment%202%20Images/1.png)

In [1]:
# 1 (a)
import numpy as np

S = np.array([
    [1, 2],
    [2, 1],
    [3, 2],
    [4, 1]
])

A = np.array([
    [1, 2],
    [2, 1]
])

X = S @ A.T
print("Mixed Signals (X):\n", X)


# 1 (b)
from sklearn.decomposition import FastICA

ica = FastICA(n_components=2, random_state=0)
S_recovered = ica.fit_transform(X)

print("\nRecovered Signals:\n", S_recovered)


# 1 (c)
print("\nOriginal Signals:\n", S)
print("\nRecovered Signals (scaled/permuted):\n", S_recovered)

Mixed Signals (X):
 [[5 4]
 [4 5]
 [7 8]
 [6 9]]

Recovered Signals:
 [[-1.00000066  0.99999934]
 [-0.99999934 -1.00000066]
 [ 0.99999934  1.00000066]
 [ 1.00000066 -0.99999934]]

Original Signals:
 [[1 2]
 [2 1]
 [3 2]
 [4 1]]

Recovered Signals (scaled/permuted):
 [[-1.00000066  0.99999934]
 [-0.99999934 -1.00000066]
 [ 0.99999934  1.00000066]
 [ 1.00000066 -0.99999934]]


![Image](./Data/Assignment%202%20Images/2.png)

In [2]:
# 2 (a)
import numpy as np
from keras.models import Model
from keras.layers import Input, Dense

# Ignore TensorFlow warnings
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

data = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]
], dtype=float)

input_layer = Input(shape=(5,))
encoded = Dense(2, activation='relu')(input_layer)
decoded = Dense(5, activation='linear')(encoded)

autoencoder = Model(input_layer, decoded)
encoder = Model(input_layer, encoded)


# 2 (b)
autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(data, data, epochs=200, verbose=0)


# 2 (c)
encoded_data = encoder.predict(data)
print("Encoded Representation:\n", encoded_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
Encoded Representation:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


![Image](./Data/Assignment%202%20Images/3.png)

In [3]:
# 3 (a)
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

X, y = make_classification(n_samples=120, n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1, random_state=42)

labeled_idx = list(range(10))
unlabeled_idx = list(range(10, 120))


# 3 (b) (c) (d) (e)
for _ in range(8):
    model = LogisticRegression()
    model.fit(X[labeled_idx], y[labeled_idx])
    
    probs = model.predict_proba(X[unlabeled_idx])
    uncertainty = np.abs(probs[:, 0] - 0.5)
    
    query_idx = np.argmin(uncertainty)
    selected = unlabeled_idx[query_idx]
    
    labeled_idx.append(selected)
    unlabeled_idx.remove(selected)

print("Final labeled indices:", labeled_idx)

Final labeled indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 116, 94, 108, 62, 36, 103, 33, 106]


![Image](./Data/Assignment%202%20Images/4.png)

In [4]:
# 4 (a)
import numpy as np

X = np.array([1, 3, 5])
centers = np.array([2, 4])
sigma = 1

distances = np.abs(X[:, np.newaxis] - centers)
print("Euclidean Distances:\n", distances)


# 4 (b)
rbf = np.exp(-(distances**2) / (2 * sigma**2))
print("\nGaussian RBF:\n", rbf)


# 4 (c)
hidden_output = rbf
print("\nHidden Layer Output:\n", hidden_output)

Euclidean Distances:
 [[1 3]
 [1 1]
 [3 1]]

Gaussian RBF:
 [[0.60653066 0.011109  ]
 [0.60653066 0.60653066]
 [0.011109   0.60653066]]

Hidden Layer Output:
 [[0.60653066 0.011109  ]
 [0.60653066 0.60653066]
 [0.011109   0.60653066]]


![Image](./Data/Assignment%202%20Images/5.png)

In [5]:
# 5 (a)
from itertools import combinations

transactions = [
    {'A', 'B'},
    {'A', 'C'},
    {'B', 'C'},
    {'A', 'B', 'C'}
]

items = sorted(set().union(*transactions))

C1 = [{item} for item in items]
C2 = [set(c) for c in combinations(items, 2)]
C3 = [set(c) for c in combinations(items, 3)]


# 5 (b)
def get_support(itemset):
    return sum(1 for t in transactions if itemset.issubset(t))

support_C1 = {tuple(i): get_support(set(i)) for i in C1}
support_C2 = {tuple(i): get_support(set(i)) for i in C2}
support_C3 = {tuple(i): get_support(set(i)) for i in C3}


# 5 (c)
min_support = 2

L1 = {k: v for k, v in support_C1.items() if v >= min_support}
L2 = {k: v for k, v in support_C2.items() if v >= min_support}
L3 = {k: v for k, v in support_C3.items() if v >= min_support}

print("Frequent 1-itemsets:", L1)
print("Frequent 2-itemsets:", L2)
print("Frequent 3-itemsets:", L3)

Frequent 1-itemsets: {('A',): 3, ('B',): 3, ('C',): 3}
Frequent 2-itemsets: {('B', 'A'): 2, ('C', 'A'): 2, ('B', 'C'): 2}
Frequent 3-itemsets: {}


![Image](./Data/Assignment%202%20Images/6.png)

In [6]:
# 6 (a)
transactions = [
    {'A', 'B'},
    {'A', 'C'},
    {'B', 'C'}
]

tid_list = {}
for tid, transaction in enumerate(transactions):
    for item in transaction:
        if item not in tid_list:
            tid_list[item] = set()
        tid_list[item].add(tid)

print("TID List:", tid_list)


# 6 (b)
from itertools import combinations

intersections = {}
items = list(tid_list.keys())

for r in range(2, len(items) + 1):
    for combo in combinations(items, r):
        intersect = set.intersection(*(tid_list[i] for i in combo))
        intersections[combo] = intersect

print("\nIntersections:", intersections)


# 6 (c)
min_support = 2

frequent_itemsets = {}

for item, tids in tid_list.items():
    if len(tids) >= min_support:
        frequent_itemsets[(item,)] = tids

for combo, tids in intersections.items():
    if len(tids) >= min_support:
        frequent_itemsets[combo] = tids

print("\nFrequent Itemsets:", frequent_itemsets)

TID List: {'B': {0, 2}, 'A': {0, 1}, 'C': {1, 2}}

Intersections: {('B', 'A'): {0}, ('B', 'C'): {2}, ('A', 'C'): {1}, ('B', 'A', 'C'): set()}

Frequent Itemsets: {('B',): {0, 2}, ('A',): {0, 1}, ('C',): {1, 2}}


![Image](./Data/Assignment%202%20Images/6_2.png)

In [7]:
# 6 (a)
import numpy as np
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from scipy.stats import mode

X, y = make_classification(n_samples=400, n_features=4, random_state=42)

n_models = 10
models = []
bootstrap_samples = []

for _ in range(n_models):
    indices = np.random.choice(len(X), size=len(X), replace=True)
    X_sample = X[indices]
    y_sample = y[indices]
    bootstrap_samples.append((X_sample, y_sample))


# 6 (b)
for X_sample, y_sample in bootstrap_samples:
    model = DecisionTreeClassifier()
    model.fit(X_sample, y_sample)
    models.append(model)


# 6 (c)
predictions = []

for model in models:
    preds = model.predict(X)
    predictions.append(preds)

predictions = np.array(predictions)
final_preds = mode(predictions, axis=0).mode.flatten()


# 6 (d)
accuracy = accuracy_score(y, final_preds)
print("Bagging Accuracy:", accuracy)

Bagging Accuracy: 0.9925


![Image](./Data/Assignment%202%20Images/7.png)

In [8]:
# 10 (a)
from sklearn.datasets import make_classification
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X, y = make_classification(n_samples=120, n_features=2, n_redundant=0, n_informative=2, random_state=42)

boost = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=50,
    random_state=42
)

boost.fit(X, y)


# 10 (b)
sample_weights = boost.estimator_weights_
print("Estimator Weights (focus on misclassified samples):\n", sample_weights)


# 10 (c)
y_pred_boost = boost.predict(X)
boost_acc = accuracy_score(y, y_pred_boost)


# 10 (d)
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=50,
    random_state=42
)

bag.fit(X, y)
y_pred_bag = bag.predict(X)
bag_acc = accuracy_score(y, y_pred_bag)

print("\nBoosting Accuracy:", boost_acc)
print("Bagging Accuracy:", bag_acc)

Estimator Weights (focus on misclassified samples):
 [2.39789527 0.93546065 0.66950542 0.4980866  0.39745866 0.49294845
 0.43342478 0.55339274 0.37200302 0.32752287 0.28113025 0.27724738
 0.42014173 0.53769538 0.55752145 0.26253582 0.47455721 0.53410591
 0.53693621 0.22324047 0.22278969 0.2003847  0.18208558 0.3723002
 0.2716749  0.25828353 0.25379147 0.39590274 0.2466432  0.11641961
 0.13151917 0.23095517 0.20696052 0.10028245 0.11551523 0.35842932
 0.43450986 0.4320673  0.26251174 0.39792496 0.41569023 0.14930092
 0.40779518 0.19712083 0.18617098 0.35897013 0.21162716 0.11558291
 0.20445783 0.37806007]

Boosting Accuracy: 0.925
Bagging Accuracy: 1.0


![Image](./Data/Assignment%202%20Images/8.png)

In [9]:
# 11 (a)
import random

states = [0, 1, 2, 3]
actions = ['Left', 'Right']


# 11 (b)
current_state = 0
steps = 10
transitions = []

for _ in range(steps):
    action = random.choice(actions)
    
    if action == 'Left':
        next_state = max(0, current_state - 1)
    else:
        next_state = min(3, current_state + 1)
    
    transitions.append((current_state, action, next_state))
    current_state = next_state


# 11 (c)
rewards = []
for (_, _, next_state) in transitions:
    reward = 1 if next_state == 3 else 0
    rewards.append(reward)


# 11 (d)
for i, (state, action, next_state) in enumerate(transitions):
    print(f"Step {i+1}: {state} --{action}--> {next_state}, Reward: {rewards[i]}")

Step 1: 0 --Left--> 0, Reward: 0
Step 2: 0 --Right--> 1, Reward: 0
Step 3: 1 --Left--> 0, Reward: 0
Step 4: 0 --Right--> 1, Reward: 0
Step 5: 1 --Left--> 0, Reward: 0
Step 6: 0 --Left--> 0, Reward: 0
Step 7: 0 --Left--> 0, Reward: 0
Step 8: 0 --Right--> 1, Reward: 0
Step 9: 1 --Right--> 2, Reward: 0
Step 10: 2 --Left--> 1, Reward: 0


![Image](./Data/Assignment%202%20Images/9.png)

In [10]:
# 12 (a)
import numpy as np
import random

epsilon = 0.2
actions = [0, 1]  # example actions
q_values = np.zeros(len(actions))


# 12 (b)
explore_count = 0
exploit_count = 0
iterations = 20

for _ in range(iterations):
    if random.random() < epsilon:
        action = random.choice(actions)
        explore_count += 1
    else:
        action = np.argmax(q_values)
        exploit_count += 1
    
    reward = random.random()
    q_values[action] += 0.1 * (reward - q_values[action])


# 12 (c)
exploration_steps = explore_count
exploitation_steps = exploit_count


# 12 (d)
print("Exploration steps:", exploration_steps)
print("Exploitation steps:", exploitation_steps)
print("Final Q-values:", q_values)

Exploration steps: 2
Exploitation steps: 18
Final Q-values: [0.40573092 0.04536429]


![Image](./Data/Assignment%202%20Images/10.png)

In [11]:
# 13 (a)
states = [0, 1, 2, 3]
actions = ['Left', 'Right']

policy_deterministic = {
    0: 'Right',
    1: 'Right',
    2: 'Right',
    3: 'Left'
}


# 13 (b)
policy_stochastic = {}

for s in states:
    probs = {a: 0.0 for a in actions}
    probs[policy_deterministic[s]] = 1.0
    policy_stochastic[s] = probs


# 13 (c)
for s in states:
    print(f"State {s}: {policy_stochastic[s]}")

State 0: {'Left': 0.0, 'Right': 1.0}
State 1: {'Left': 0.0, 'Right': 1.0}
State 2: {'Left': 0.0, 'Right': 1.0}
State 3: {'Left': 1.0, 'Right': 0.0}


![Image](./Data/Assignment%202%20Images/11.png)

![Image](./Data/Assignment%202%20Images/11_1.png)

In [12]:
# 14 (a)
import numpy as np
import random

states = ['Sunny', 'Rainy']
P = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])

current_state = 0
days = 10
sequence = [states[current_state]]

for _ in range(days - 1):
    current_state = np.random.choice([0, 1], p=P[current_state])
    sequence.append(states[current_state])

print("Weather sequence:", sequence)


# 14 (b)
from collections import Counter

freq = Counter(sequence)
print("\nState frequencies:", freq)


# 14 (c)
row_sums = P.sum(axis=1)
print("\nRow sums (should be 1):", row_sums)

Weather sequence: ['Sunny', 'Rainy', 'Rainy', 'Rainy', 'Sunny', 'Sunny', 'Rainy', 'Rainy', 'Rainy', 'Sunny']

State frequencies: Counter({'Rainy': 6, 'Sunny': 4})

Row sums (should be 1): [1. 1.]


![Image](./Data/Assignment%202%20Images/12.png)

In [13]:
# 15 (a)
import numpy as np

states = ['S1', 'S2']
R = np.array([5, 2])
gamma = 0.9

P = np.array([
    [0.5, 0.5],
    [0.2, 0.8]
])


# 15 (b)
I = np.eye(len(states))
V = np.linalg.inv(I - gamma * P) @ R

print("Value Function:", V)


# 15 (c)
for i, s in enumerate(states):
    print(f"State {s} Value:", V[i])

Value Function: [31.50684932 27.39726027]
State S1 Value: 31.506849315068514
State S2 Value: 27.39726027397263


![Image](./Data/Assignment%202%20Images/13.png)

In [14]:
# 16 (a)
import numpy as np

states = [0, 1, 2]
actions = ['Left', 'Right']

V = np.zeros(len(states))
gamma = 0.9


# 16 (b)
def get_next_state_reward(s, a):
    if a == 'Left':
        next_state = max(0, s - 1)
    else:
        next_state = min(2, s + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward

theta = 1e-4

while True:
    delta = 0
    new_V = V.copy()
    
    for s in states:
        v = 0
        for a in actions:
            next_state, reward = get_next_state_reward(s, a)
            v += 0.5 * (reward + gamma * V[next_state])
        
        new_V[s] = v
        delta = max(delta, abs(V[s] - new_V[s]))
    
    V = new_V
    print("Updated V:", V)
    
    if delta < theta:
        break


# 16 (c)
print("\nFinal Value Function:", V)

Updated V: [0.  0.5 0.5]
Updated V: [0.225 0.725 0.95 ]
Updated V: [0.4275  1.02875 1.25375]
Updated V: [0.6553125 1.2565625 1.527125 ]
Updated V: [0.86034375 1.48209688 1.75265937]
Updated V: [1.05409828 1.67585141 1.95564031]
Updated V: [1.22847736 1.85438237 2.13417127]
Updated V: [1.38728688 2.01319188 2.29484914]
Updated V: [1.53021544 2.15696121 2.43861846]
Updated V: [1.65922949 2.28597526 2.56801085]
Updated V: [1.77534214 2.40225815 2.68429375]
Updated V: [1.87992013 2.50683615 2.78894836]
Updated V: [1.97404033 2.60099082 2.88310303]
Updated V: [2.05876402 2.68571451 2.96784223]
Updated V: [2.13501534 2.76197281 3.04410053]
Updated V: [2.20364467 2.83060214 3.112733  ]
Updated V: [2.26541106 2.89236995 3.17450082]
Updated V: [2.32100146 2.94796035 3.23009185]
Updated V: [2.37103281 2.99799199 3.28012349]
Updated V: [2.41606116 3.04302033 3.32515196]
Updated V: [2.45658667 3.0835459  3.36567753]
Updated V: [2.49305966 3.12001889 3.40215055]
Updated V: [2.52588535 3.15284459 3.

![Image](./Data/Assignment%202%20Images/14.png)

In [15]:
# 17 (a)
import numpy as np

states = [0, 1, 2]
actions = ['Left', 'Right']

V = np.array([0.0, 0.0, 0.0])  # replace with final V from Q16 if needed
gamma = 0.9


# 17 (b)
def get_next_state_reward(s, a):
    if a == 'Left':
        next_state = max(0, s - 1)
    else:
        next_state = min(2, s + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward

policy = {}

for s in states:
    action_values = {}
    
    for a in actions:
        next_state, reward = get_next_state_reward(s, a)
        action_values[a] = reward + gamma * V[next_state]
    
    best_action = max(action_values, key=action_values.get)
    policy[s] = best_action


# 17 (c)
for s in states:
    print(f"State {s}: {policy[s]}")

State 0: Left
State 1: Right
State 2: Right


![Image](./Data/Assignment%202%20Images/15.png)

In [16]:
# 18 (a)
import numpy as np

states = [0, 1, 2]
actions = ['Left', 'Right']
gamma = 0.9

V = np.zeros(len(states))


# 18 (b)
def get_next_state_reward(s, a):
    if a == 'Left':
        next_state = max(0, s - 1)
    else:
        next_state = min(2, s + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward


# 18 (c)
theta = 1e-4

while True:
    delta = 0
    new_V = V.copy()
    
    for s in states:
        action_values = []
        
        for a in actions:
            next_state, reward = get_next_state_reward(s, a)
            action_values.append(reward + gamma * V[next_state])
        
        best_value = max(action_values)
        new_V[s] = best_value
        delta = max(delta, abs(V[s] - new_V[s]))
    
    V = new_V
    print("Updated V:", V)
    
    if delta < theta:
        break


# 18 (d)
policy = {}

for s in states:
    action_values = {}
    
    for a in actions:
        next_state, reward = get_next_state_reward(s, a)
        action_values[a] = reward + gamma * V[next_state]
    
    policy[s] = max(action_values, key=action_values.get)

print("\nOptimal Value Function:", V)
print("Optimal Policy:", policy)

Updated V: [0. 1. 1.]
Updated V: [0.9 1.9 1.9]
Updated V: [1.71 2.71 2.71]
Updated V: [2.439 3.439 3.439]
Updated V: [3.0951 4.0951 4.0951]
Updated V: [3.68559 4.68559 4.68559]
Updated V: [4.217031 5.217031 5.217031]
Updated V: [4.6953279 5.6953279 5.6953279]
Updated V: [5.12579511 6.12579511 6.12579511]
Updated V: [5.5132156 6.5132156 6.5132156]
Updated V: [5.86189404 6.86189404 6.86189404]
Updated V: [6.17570464 7.17570464 7.17570464]
Updated V: [6.45813417 7.45813417 7.45813417]
Updated V: [6.71232075 7.71232075 7.71232075]
Updated V: [6.94108868 7.94108868 7.94108868]
Updated V: [7.14697981 8.14697981 8.14697981]
Updated V: [7.33228183 8.33228183 8.33228183]
Updated V: [7.49905365 8.49905365 8.49905365]
Updated V: [7.64914828 8.64914828 8.64914828]
Updated V: [7.78423345 8.78423345 8.78423345]
Updated V: [7.90581011 8.90581011 8.90581011]
Updated V: [8.0152291 9.0152291 9.0152291]
Updated V: [8.11370619 9.11370619 9.11370619]
Updated V: [8.20233557 9.20233557 9.20233557]
Updated V:

![Image](./Data/Assignment%202%20Images/18.png)

In [17]:
# 19 (a)
import random
import numpy as np

states = [0, 1, 2]
actions = ['Left', 'Right']
gamma = 0.9

def get_next_state_reward(s, a):
    if a == 'Left':
        next_state = max(0, s - 1)
    else:
        next_state = min(2, s + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward

episodes = []

for _ in range(5):
    episode = []
    state = random.choice(states)
    
    for _ in range(5):
        action = random.choice(actions)
        next_state, reward = get_next_state_reward(state, action)
        episode.append((state, reward))
        state = next_state
    
    episodes.append(episode)


# 19 (b)
returns = []

for episode in episodes:
    G = 0
    episode_returns = []
    
    for t in reversed(range(len(episode))):
        _, reward = episode[t]
        G = reward + gamma * G
        episode_returns.insert(0, G)
    
    returns.append(episode_returns)


# 19 (c)
value_sum = {s: 0 for s in states}
value_count = {s: 0 for s in states}

for episode, Gs in zip(episodes, returns):
    for (state, _), G in zip(episode, Gs):
        value_sum[state] += G
        value_count[state] += 1

V = {s: value_sum[s] / value_count[s] if value_count[s] > 0 else 0 for s in states}

print("Episodes:", episodes)
print("\nReturns:", returns)
print("\nEstimated Value Function:", V)

Episodes: [[(2, 0), (1, 1), (2, 1), (2, 1), (2, 1)], [(1, 1), (2, 0), (1, 0), (0, 0), (1, 0)], [(2, 0), (1, 1), (2, 1), (2, 1), (2, 0)], [(1, 1), (2, 1), (2, 0), (1, 1), (2, 0)], [(0, 0), (1, 1), (2, 1), (2, 0), (1, 0)]]

Returns: [[3.0951, 3.439, 2.71, 1.9, 1.0], [1.0, 0.0, 0.0, 0.0, 0.0], [2.439, 2.71, 1.9, 1.0, 0.0], [2.629, 1.81, 0.9, 1.0, 0.0], [1.71, 1.9, 1.0, 0.0, 0.0]]

Estimated Value Function: {0: 0.855, 1: 1.4086666666666667, 2: 1.26815}


![Image](./Data/Assignment%202%20Images/17.png)

In [18]:
# 20 (a)
import numpy as np
import random

states = [0, 1, 2]
actions = ['Left', 'Right']

Q = np.zeros((len(states), len(actions)))

alpha = 0.1
gamma = 0.9


# 20 (b) (c) (d)
def get_next_state_reward(s, a):
    if a == 'Left':
        next_state = max(0, s - 1)
    else:
        next_state = min(2, s + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward

episodes = 20

for _ in range(episodes):
    state = random.choice(states)
    
    for _ in range(10):
        action_idx = random.choice([0, 1])
        action = actions[action_idx]
        
        next_state, reward = get_next_state_reward(state, action)
        
        best_next = np.max(Q[next_state])
        
        Q[state, action_idx] += alpha * (reward + gamma * best_next - Q[state, action_idx])
        
        state = next_state


# 20 (e)
print("Final Q-table:\n", Q)

Final Q-table:
 [[1.1596798  1.99783232]
 [1.12677222 2.88292927]
 [2.01278556 2.75019664]]


##### Submitted By->

- Name: Amulya Shrivastava
- Regd No: 2341019456
- Section: 23412F3
- Serial No: 59
- Semester: 6th
- Branch: B.Tech CSE Core